services:
  - type: web
    name: student-report-prediction
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run "Deploying ML Model/Report Prediction Web App.py" --server.port $PORT --server.address 0.0.0.0
